### ISSUE TITLE
ImportError: No module named 'functional'

### ISSUE THREAD

**Issue by LiangGou** [fastforwardlabs/vae-tf#4]
I am using TensorFlow with Python 3.4.5. 
While importing functional, I got:

ImportError: No module named 'functional'

It turns out the 'functional' module is not available for  Python 3.4.5. Do you have any insights to solve this ?

Thx!

**Comment by LiangGou** [comment]
Or maybe some alternative to the function of compose in the 'functional' module?

**Comment by meereeum** [comment]
@LiangGou, there are some good suggestions here: https://gist.github.com/rossdylan/3287138

**Comment by LiangGou** [comment]
thank you,  @meereeum !!
